module.exports = {
  FIRST_ALPHABET_CHAR_CODE_UPPERCASE: 65,
  LAST_ALPHABET_CHAR_CODE_UPPERCASE: 90,
  FIRST_ALPHABET_CHAR_CODE_LOWERCASE: 97,
  LAST_ALPHABET_CHAR_CODE_LOWERCASE: 122,
  ACTION_TYPES: {
    ENCODE: "encode",
    DECODE: "decode",
  },
};
